- cmd/info.go
- cmd/ping.go
- cmd/root.go
- cmd/version.go
- go.mod
- go.sum
- main.go
- utils/utils.go
- validation/utils.go
Added basic configuration commands: `version`, `ping`, `info`
To test:
- `go run .`
- `go run . ping`
- `go run . info --json`
> cli: add basic configuration commands

- cmd/info.go
- cmd/list.go
- cmd/ping.go
- cmd/root.go
- cmd/version.go
- cmd/version_test.go
- main.go
- utils/utils.go
- Updates commands by wrapping initialization inside a function (same technique used in `helm`, `kind`, `hugo`, etc..) to make it easier to test it
- Introduce some basic unit test for the `version` command as an example how to test cobra CLI commands
To test:
```
go test -v ./...
```
> cli: introduce unit tests for the `version` command

- .gitignore
- AUTHORS.rst
- cmd/info.go
- cmd/list.go
- cmd/ping.go
closes #11
Hides the access token from the command description when using `--help`. Did it by having our own logic for a default value, instead of using Cobra's feature
> cli: Hide access token from the command description

- client/client.go
- cmd/info.go
- cmd/list.go
- cmd/ping.go
closes #12
Prevents REANA server URL from being validated when not used, by transforming ApiClient into a function, so that it is only initialized when a command actually needs it
> cli: fix reana server url being verified when not used

- CONTRIBUTING.rst
- Makefile
- client/operations/create_gitlab_webhook_parameters.go
- client/operations/create_gitlab_webhook_responses.go
- client/operations/delete_gitlab_webhook_parameters.go
- client/operations/delete_gitlab_webhook_responses.go
- client/operations/get_workflows_parameters.go
- client/operations/operations_client.go
- cmd/info.go
- cmd/list.go
- cmd/ping.go
- cmd/version.go
Introduces a Makefile that could be used to run some custom build tasks.
Some usage examples:
```
$ make test
$ make build
$ make generate-api-client
```
closes https://github.com/reanahub/reana-client-go/issues/5
> setup: add a Makefile for some custom build tasks

- client/operations/get_files_responses.go
- client/operations/get_workflow_disk_usage_responses.go
- client/operations/get_workflows_parameters.go
- client/operations/get_workflows_responses.go
- cmd/du.go
- cmd/list.go
- utils/display.go
- utils/utils.go
Contributes to #27 
Introduces all the flags functionality, except format, sort and json. Some other features, such as the session headers, were left with a todo mark.
This seemed like a good mark to ask for a review. The following work will be to fix all the TODOs and implement the flags that are still missing
> cli: implement more flags in the list command

- client/operations/get_workflows_responses.go
- cmd/list.go
closes #27 
Adds support for the missing headers in the `list` table, related to interactive sessions.
Additionally, updates swagger API and fixes the json output that was not working correctly
> List sessions headers and json output

- client/client.go
- cmd/close.go
- cmd/du.go
- cmd/info.go
- cmd/list.go
- cmd/open.go
- cmd/ping.go
- cmd/root.go
- utils/display.go
- utils/utils.go
- validation/utils.go
Changes the logic we use to handle errors. Now, instead of simply printing an error to the console and exiting the program, the errors are returned to the calling function.
In the end, the error is handled by Cobra, using the RunE function option.
closes #46
> cli: improve error handling in the command functions

- cmd/close.go
- cmd/du.go
- cmd/info.go
- cmd/list.go
- cmd/open.go
- cmd/ping.go
- cmd/root.go
- cmd/version.go
- cmd/version_test.go
- utils/display.go
- utils/utils.go
closes #24
The strategy was:
- Change the Cobra's output to `os.Stdout`, since it uses `Stderr` by default. This only needed to be done at the root command
- In every command, change the `fmt` commands to `cmd` (e.g. `cmd.PrintLn()`)
- In `utils` or other functions without accces to `cmd`, pass the output through a parameter and use it
> cli: add a way to control the output stream

- cmd/close.go
- cmd/open.go
- utils/display.go
- utils/display_test.go
closes https://github.com/reanahub/reana-client-go/issues/2
Built on top of [cli: implement loglevel flag](https://github.com/reanahub/reana-client-go/pull/54)
This PR introduces an utility similar to [display_message() in Python client](https://github.com/reanahub/reana-client/blob/master/reana_client/printer.py#L21) to colorize the output in `reana-client-go`
> cli: add display message utility

- AUTHORS.rst
- client/client.go
- cmd/ping_test.go
Related to #3 
This PR introduces a new test for the `ping` command, mainly to showcase one of the options we have to mock the API calls made to reana-server.
A few comments:
1. We should consider reading the environment variables once at the beginning of the execution and saving them in a config variable accessible by the various commands. In this way, when testing we would not have to set and unset environment variables, which makes our tests fragile and difficult to run in parallel.
2. We should consider wrapping the creation of a test TLS server to make it easier to use and reuse it in many tests
3. To check the command's output from the test, the command needs to print to `cmd.OutOrStdout()`. The output is not captured when using `fmt.Println` (or similar).
> ping: add test

- cmd/close.go
- cmd/logs.go
- cmd/open.go
- cmd/ping.go
- main.go
- utils/display.go
- utils/utils.go
Adds logs and colors to the messages that were missing them, according mostly to the Python client.
closes https://github.com/reanahub/reana-client-go/issues/62
> cli: add missing logs and messages colors

- cmd/diff.go
- cmd/diff_test.go
- cmd/root.go
- utils/display_test.go
- utils/utils.go
- utils/utils_test.go
> cli: implement `diff` command

- .github/codecov.yml
- .github/workflows/ci.yml
- .gitignore
- Makefile
- README.rst
Exposes a code coverage badge on README.rst and configures pull requests with coverage information.
closes #112
> docs: expose code coverage

- cmd/profiling.go
- cmd/root.go
- go.mod
closes https://github.com/reanahub/reana-client-go/issues/101
to test:
```
go run . list --profile=cpu
go tool pprof -text profile.pprof
```
> cli: add generic profiler

- cmd/restart.go
- cmd/root.go
addresses https://github.com/reanahub/reana-client-go/issues/122
Please note that this PR misses implementation of ``--file`` flag, because it requires [loading and validating](https://github.com/reanahub/reana-client/blob/master/reana_client/cli/workflow.py#L601-L604) the specification file. It could be tackled later once we make the clients thin and refactor the spec upload logic to send the whole yaml file to the server side and process it there.
> cli: implement restart command

- client/operations/get_workflow_specification_responses.go
- cmd/root.go
- cmd/upload.go
- cmd/upload_test.go
- pkg/workflows/manager.go
- testdata/inputs/upload_success.json
closes https://github.com/reanahub/reana-client-go/issues/131
To test:
```
$ go build
$ cd ../reana-demo-helloworld 
$ reana-client create -w upload-test
$ ../reana-client-go/reana-client-go upload -w upload-test reana.yaml -l DEBUG # check https://localhost:30443 for the reana.yaml file to be present in the workspace
$ ../reana-client-go/reana-client-go upload -w upload-test -l DEBUG # check https://localhost:30443 for all the workspace input files to be present in the workspace
```
Please note that https://github.com/reanahub/reana-client-go/issues/134 will be tackled in a separate PR
> cli: implement upload command

- .github/codecov.yml
Adds desired targets and threshold values for code coverage tests in pull requests.
Removes custom code coverage range to fall back to codecov defaults.
> codecov: add threshold values

- client/operations/get_workflow_status_responses.go
- client/operations/get_workflows_responses.go
- cmd/list.go
- cmd/status.go
- pkg/workflows/utils.go
- pkg/workflows/utils_test.go
Closes reanahub/reana-client#699
> fix(status): correctly display duration of stopped workflows (#156)

- client/operations/get_workflow_logs_responses.go
- cmd/logs.go
- cmd/logs_test.go
- cmd/root_test.go
- pkg/config/config.go
- testdata/inputs/logs_complete_live.json
- testdata/inputs/logs_malformed.json
- testdata/inputs/logs_running.json
- testdata/inputs/page.html
Closes https://github.com/reanahub/reana-client/issues/730
Similar to https://github.com/reanahub/reana-client/pull/731 but in go.
> feat(cli): add --follow flag to logs command (#161)

- client/operations/info_responses.go
- client/operations/set_workflow_status_parameters.go
- client/operations/set_workflow_status_responses.go
- client/operations/start_workflow_responses.go
- cmd/info.go
- testdata/inputs/info_dask.json
Following the recent change that makes the number of threads configurable for Dask workers, this commit adds the updates the `/api/info/` endpoint to include the two introduces parameters:
* `dask_cluster_default_single_worker_threads`: Defines the default number of threads per single Dask worker.
* `dask_cluster_max_single_worker_threads`: Sets an upper limit on the number of threads per single Dask worker.
Closes reanahub/reana#874
> feat(info): display information about Dask worker threads
