reanahub/reana-client-go

cmd/du.go
cmd/list.go
utils/utils.go

closes #27
Implement the remaining flags in the `list` command: `sort` and `format`

cli: sort and format in list command

---

cmd/close.go
cmd/du.go
cmd/info.go
cmd/list.go
cmd/open.go
cmd/root.go
utils/utils.go
validation/utils.go

 cli: implement commands to open and close interactive sessions

---

cmd/du.go
cmd/list.go
cmd/logs.go
cmd/root.go
utils/utils.go

Logs command

---

cmd/close.go
cmd/du.go
cmd/info.go
cmd/list.go
cmd/logs.go
cmd/open.go
cmd/ping.go

cli: use options struct for flags and configuration

---

AUTHORS.rst
client/client.go
cmd/close.go
cmd/du.go
cmd/info.go
cmd/list.go
cmd/logs.go
cmd/open.go
cmd/ping.go
cmd/root.go
cmd/version.go
main.go
utils/data.go
utils/display.go
utils/utils.go
validation/utils.go

cli: add documentation

---

client/operations/get_workflow_status_responses.go
cmd/list.go
cmd/logs.go
cmd/open.go
cmd/root.go
cmd/status.go
utils/filters.go
utils/utils.go

cli: implement status command

---

client/operations/get_files_responses.go
cmd/close.go
cmd/du.go
cmd/info.go
cmd/list.go
cmd/logs.go
cmd/ls.go
cmd/open.go
cmd/ping.go
cmd/root.go
cmd/status.go
cmd/version.go

closes #20
This openapi changes also contain the ones in #65 so merge it afterwards

cli: implement ls command

---

Makefile
utils/utils.go
utils/utils_test.go
validation/utils.go
validation/utils_test.go

cli: unit tests for validation/utils.go and utils/utils.go

---

cmd/ping_test.go
cmd/root_test.go
cmd/version_test.go
utils/utils.go
validation/utils.go
validation/utils_test.go

tests: function to test commands and unit tests for root.go

---

cmd/ping_test.go
cmd/root_test.go
utils/display_test.go
utils/filters_test.go
utils/utils_test.go
validation/utils_test.go

tests: unit tests for utils/filters.go and name subtests

---

Makefile
utils/data_test.go
utils/display_test.go

tests: unit tests for utils/display.go and utils/data.go

---

client/client.go
cmd/close_test.go
cmd/info_test.go
cmd/ping_test.go
cmd/root_test.go

tests: unit tests for info and close commands

---

cmd/close_test.go
cmd/du_test.go
cmd/open_test.go
cmd/root_test.go

tests: unit tests for open and du commands

---

cmd/close_test.go
cmd/du_test.go
cmd/logs.go
cmd/logs_test.go
cmd/ls_test.go
cmd/open_test.go
cmd/root_test.go

tests: unit tests for ls and logs commands

---

cmd/list.go
cmd/list_test.go
cmd/ls_test.go
cmd/status.go
cmd/status_test.go

tests: unit tests for status and list commands

---

Makefile
pkg/config/config_test.go
pkg/datautils/datautils_test.go
pkg/errorhandler/errorhandler_test.go
pkg/validator/validator_test.go
pkg/workflows/utils_test.go

tests: implement RemoveFromSlice unit tests

---

client/operations/get_workflow_status_responses.go
client/operations/info_responses.go
cmd/info.go
cmd/info_test.go
cmd/status.go
cmd/status_test.go
pkg/validator/validator_test.go

cli: update info command with new information

---

cmd/list.go

cli: only set include flags when user specifies them in list command

---

client/operations/set_workflow_status_parameters.go
client/operations/set_workflow_status_responses.go
cmd/delete.go
cmd/delete_test.go
cmd/root.go
pkg/formatter/formatter_test.go
pkg/workflows/manager.go
pkg/workflows/manager_test.go
pkg/workflows/utils.go
pkg/workflows/utils_test.go

cli: implement delete command

---

client/client.go
client/operations/get_workflow_parameters_responses.go
client/operations/start_workflow_parameters.go
client/operations/start_workflow_responses.go
cmd/close_test.go
cmd/delete_test.go
cmd/diff_test.go
cmd/du_test.go
cmd/info_test.go
cmd/list_test.go
cmd/logs_test.go
cmd/ls_test.go
cmd/open_test.go
cmd/ping.go
cmd/ping_test.go
cmd/quota_show_test.go
cmd/root.go
cmd/root_test.go
cmd/start.go
cmd/start_test.go
cmd/status.go
cmd/status_test.go
pkg/config/config.go
pkg/formatter/formatter_test.go
pkg/validator/validator.go
pkg/validator/validator_test.go
pkg/workflows/manager.go

cli: implement start command

---

cmd/list_test.go
pkg/displayer/displayer.go

tables: remove padding from tables and align columns left

---

cmd/root.go
cmd/secrets_delete.go
cmd/secrets_delete_test.go

cli: implement secrets-delete command 

---

cmd/root.go
cmd/secrets_list.go
cmd/secrets_list_test.go

cli: implement secrets-list command

---

client/operations/delete_file_responses.go
client/operations/operations_client.go
cmd/rm.go
cmd/rm_test.go
cmd/root.go
cmd/root_test.go
main.go
pkg/config/config.go

cli: implement rm command

---

client/operations/move_files_responses.go
cmd/mv.go
cmd/mv_test.go
cmd/root.go

cli: implement mv command

---

cmd/quota_show_test.go
cmd/root.go
cmd/secrets_add.go
cmd/secrets_add_test.go
pkg/datautils/datautils.go
pkg/datautils/datautils_test.go
pkg/filterer/filterer.go
pkg/validator/validator.go
pkg/validator/validator_test.go

cli: implement secrets-add command

---

cmd/start_test.go
pkg/workflows/utils.go
pkg/workflows/utils_test.go

closes #109 
Review after #120

cli: improvements in StatusChangeMessage

---

cmd/start.go
cmd/start_test.go
testdata/inputs/common_failed.json

closes #110 
Review after #117

cli: start displays errors when workflow stops unexpectedly

---

cmd/root.go
pkg/commandgroups/commandgroups.go
pkg/commandgroups/commandgroups_test.go

closes https://github.com/reanahub/reana-client-go/issues/17

cli: group commands in help message

---

cmd/restart.go
cmd/root.go
cmd/stop.go
cmd/stop_test.go
pkg/config/config.go
pkg/workflows/manager.go
testdata/inputs/stop_success.json

addresses https://github.com/reanahub/reana-client-go/issues/122

cli: implement stop command

---

client/client.go
client/operations/download_file_responses.go
cmd/download.go
cmd/download_test.go
cmd/root.go
cmd/root_test.go
pkg/config/config.go
pkg/fileutils/fileutils.go
pkg/fileutils/fileutils_test.go
pkg/workflows/manager.go
testdata/inputs/download_file_not_found.json
testdata/inputs/workflow_specification.json

closes https://github.com/reanahub/reana-client-go/issues/130

cli: implement download command

---

cmd/secrets_add.go
cmd/secrets_delete.go
cmd/secrets_delete_test.go

closes https://github.com/reanahub/reana-client/issues/637

cli: secrets-delete output message cosmetics

---

cmd/delete.go

closes https://github.com/reanahub/reana-client/issues/649

cli: modify delete command description about session deletion

---

cmd/list.go
pkg/formatter/formatter.go
pkg/formatter/formatter_test.go

cli: fix issue when sorting by run_number or human_readable size

---

cmd/download.go
cmd/download_test.go
testdata/inputs/workflow_specification_without_outputs.json

cli: fix download when workflow does not have outputs
